version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: denis
      MINIO_ROOT_PASSWORD: ddudakov
    ports:
      - "9000:9000"
      - "9001:9001"
    tmpfs:
      - /data:size=512m  # Ограничение места на диске до 512 МБ
    command: server /data --console-address ":9001"

  data_uploader:
    image: data_uploader:latest
    container_name: data_uploader
    depends_on:
      - minio
    environment:
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: denis
      MINIO_SECRET_KEY: ddudakov
      BUCKET_NAME: test-bucket
    volumes:
      - ./data_uploader:/app